add events and tag models, migration, admin
totaki/learn-python-pnz-00 pull request #13
Opened 2019-12-11 11:35 UTC by SuperSerg58

2019-12-11 11:55 UTC, totaki requested changes

2019-12-11 11:55 UTC, totaki commented on events/handler/models.py
> +    title = models.CharField(max_length=512, db_index=True)
Зачем на тут индекс?

2019-12-11 11:55 UTC, totaki commented on events/handler/models.py
> +    pass
Почему пустое?

2019-12-11 11:55 UTC, totaki commented on events/handler/models.py
> +
Надо было здесь по задаче сделать ManyToMany, кажется логичней в Event, но вот почему мне не хочется делать класс монстр из ивента

2019-12-11 14:21 UTC, SuperSerg58 commented on events/handler/models.py
> +    pass
Потому что модель Place задание для Артёма было)

2019-12-11 14:23 UTC, SuperSerg58 commented on events/handler/models.py
> +    title = models.CharField(max_length=512, db_index=True)
Для индексации, чтобы более быстрый поиск был по db я так понял.

2019-12-11 14:25 UTC, SuperSerg58 commented on events/handler/models.py
> +
Да исходя из логики, что модель Event включает в себя теги. Я посчитал его основным классом, поэтому сделал к нему.

2019-12-11 14:57 UTC, totaki commented on events/handler/models.py
> +    title = models.CharField(max_length=512, db_index=True)
Оно сейчас вообще не надо

2019-12-11 14:57 UTC, totaki commented on events/handler/models.py
> +    pass
Ок

2019-12-11 14:58 UTC, totaki commented on events/handler/models.py
> +
Я не хочу класс эвент раздувать, давай пока тут сделаем.

2019-12-11 15:06 UTC, SuperSerg58 commented on events/handler/models.py
> +    pass
Без пустого класса Place джанго дебагер ругался, когда я связывал их.

2019-12-11 15:06 UTC, SuperSerg58 commented on events/handler/models.py
> +
Принял.

2019-12-11 15:06 UTC, SuperSerg58 commented on events/handler/models.py
> +    title = models.CharField(max_length=512, db_index=True)
Принял

2019-12-12 05:10 UTC, totaki approved these changes

2019-12-12 05:10 UTC, merged