Added function save_event
totaki/learn-python-pnz-00 pull request #42
Opened 2019-12-21 16:38 UTC by kas2337

2019-12-21 17:13 UTC, totaki requested changes

2019-12-21 17:13 UTC, totaki commented on events/scheduler/save_event.py
> +            Event.objects.create(
Еще раз, тебе тут возвращается уже объект event

2019-12-21 17:13 UTC, totaki commented on events/scheduler/save_event.py
> +            Place.objects.create(
Тут тебе сразу возвращается объект place

2019-12-21 17:13 UTC, totaki commented on events/scheduler/save_event.py
> +        try:
Давай получение и создание вынесим в отдельную функцию, get_place, которая нам возвращает объект place

2019-12-21 17:13 UTC, totaki commented on events/scheduler/save_event.py
> +        db_events = Event.objects.filter(title=event['title'], event_time=event['event_time'])
Проверяй на exists

2019-12-21 17:49 UTC, kas2337 commented on events/scheduler/save_event.py
> +            print(f"The event {event['title']} is in the database")
Проверял принтом, в след коммите поправлю назад на логгера

2019-12-23 06:27 UTC, totaki requested changes
Верни логгер и ок

2019-12-23 10:09 UTC, totaki requested changes

2019-12-23 10:09 UTC, totaki commented on events/handler/tests.py
> +    def test_save_event(self):
Давай добавим второй случай еще что мы не создадим лишний эвент, если у нас придет повторно

2019-12-23 10:09 UTC, totaki commented on events/handler/tests.py
> +    def test_save_event(self):
Добавь еще 1 тест

2019-12-23 10:09 UTC, totaki commented on events/handler/tests.py
> +        event = [{
Более логично назвать events

2019-12-24 07:40 UTC, totaki approved these changes

2019-12-24 07:40 UTC, merged