Changed frontend
totaki/learn-python-pnz-00 pull request #73
Opened 2020-01-12 21:07 UTC by kas2337

2020-01-13 09:09 UTC, totaki requested changes

2020-01-13 09:09 UTC, totaki commented on frontend/src/Events.js
> +          n={next}
Давай нормальные имена props

2020-01-13 09:11 UTC, kas2337 commented on frontend/src/Events.js
> +          n={next}
ок, это в процессе, никак не мог понять из-за чего ошибка выводилась, поэтому менял имена и не вернул обратно

2020-01-13 12:40 UTC, totaki commented on frontend/src/Events.js
> +          n={next}
Сейчас понял?

2020-01-13 12:47 UTC, kas2337 commented on frontend/src/Events.js
> +          n={next}
да, с этим разобрался, я в компоненте значения кнопок передавал через props, а потом props.setURL(previous) делал и никак не мог понять почему ругается на previous

2020-01-14 10:52 UTC, totaki approved these changes

2020-01-14 10:52 UTC, merged